import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/ui/Header'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jahid Hasan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><div className='fixed top-0 right-0 z-50 w-screen'><Header/></div>{children}</body>
    </html>
  )
}